### PR TITLE
Use information inside WorkspaceSettings to determine derived data directory. 

### PR DESCRIPTION
**Pull request by drodriguez**
Works for the default DerivedData directory structure, for relative directories and for absolute directories.

Caveat: For relative directories, the rake command has to be run from the project directory, otherwise the relative path will be wrong. I could not find a way to reliabily find the project directory in the case of a project with an embedded workspace, and a workspace outside the projects.

Based on information found in http://pilky.me/view/25 and my own tests.

### CODE REVIEW

**Comment by peelman** [comment]
This doesn't work.  Well, it does, but its very fragile.

If you have a project duplicated in multiple locations, each will get its own build folder, each with the same xcworkspace reference in the info.plist, and no further way to differentiate them.

As much as I hate trolling the build.output for the file path, right now its most bulletproof method of finding this.

**Comment by drodriguez** [comment]
Can you explain a little bit your use case? This is what I tried:
1. I created a new project (TestBetaBuilder) in Xcode with the wizard, and ask for creating a Git respository.
2. I built the project.
3. I cloned the directory of the new project in a new directory (TestBetaBuilder2).
4. I built this new project.
5. My ~/Library/Developer/Xcode/DerivedData contains now two directories with the same project name, but different hashes.
6. Each of those directories info.plist entry points to each one of my directories (one to TestBetaBuilder, other to TestBetaBuilder2).

Is the situation you are describing different?

**Comment by peelman** [comment]
Ok, so I went back and did a little more testing.

Perhaps this is assumption on my part, but the problem resides in that `workspace_path (on my end) is a relative path, and never gets expanded out to a full path. So it works some of the time, but if project 2's random string is ordered above project 1's random string, it would get found first, even if we were running beta builder inside project 1.

I attempted to work around this caveat, either by expanding the workspace path, or somehow validating what we're doing, but I haven't been able to devote much time to it yet.

**Comment by drodriguez** [comment]
I’ll try to have a look at it, but I haven’t seen the case you’re describing. My DerivedData directory has around 20 Xcode projects (a couple of them repeated, one of them the TestBetaBuilder) and all of them have full absolute paths in their info.plist files. I’ll try to look how `workspace_path` ends up being relative.

**Comment by peelman** [comment]
the `workspace_path` as set by the user in the config file.  If I echo out both that variable, and the variable you get out of the plist, on mine, they will never match; one is just `ProjectName.xcworkspace` and the other is `/Path/To/Project/ProjectName.xcworkspace`.

I have some code in a branch in my fork if you want to take a look at some of the changes I'm making as I attempt to integrate all the various pull requests people have made.

**Pull request closed without merging**
